import {
  decodeBase64,
  decodeUrl,
  encodeBase64,
  encodeBase64Url,
  encodeUrl,
  escapeHtml,
  hashText,
  hexToText,
  newUuid,
  textToHex,
  unescapeHtml,
} from "./encodeTools";
import {
  escapeJson,
  formatJson,
  minifyJson,
  parseJson,
  stringifyJson,
  unescapeJson,
  validateJson,
} from "./jsonTools";
import {
  buildQuery,
  decodeJwt,
  delimitedToJson,
  hexToRgb,
  jsonToDelimited,
  parseQuery,
  parseUrl,
  rgbToHex,
  unixToUtc,
  utcToUnix,
} from "./convertTools";
import {
  countText,
  sortLines,
  stripHtml,
  toLower,
  toUpper,
  trimLines,
  uniqueLines,
} from "./textTools";
import { runSync, toolErrorMessage, type ToolDef } from "./types";

function sync(fn: (input: string) => string): ToolDef["run"] {
  return async (input) => runSync(() => fn(input));
}

const UGLY_JSON = '{"name":"Ada","skills":["json","base64"],"ok":true}';

export const TOOLS: ToolDef[] = [
  {
    id: "json-format",
    name: "Format JSON",
    category: "json",
    blurb: "Pretty-print JSON with two-space indentation.",
    placeholder: UGLY_JSON,
    sample: UGLY_JSON,
    actionLabel: "Format",
    run: sync(formatJson),
  },
  {
    id: "json-minify",
    name: "Minify JSON",
    category: "json",
    blurb: "Remove insignificant whitespace from JSON.",
    placeholder: '{\n  "name": "Ada"\n}',
    sample: '{\n  "name": "Ada",\n  "ok": true\n}',
    actionLabel: "Minify",
    run: sync(minifyJson),
  },
  {
    id: "json-escape",
    name: "Escape JSON",
    category: "json",
    blurb:
      "Escape quotes, backslashes, and newlines so the text can sit inside a JSON string. Does not add surrounding quotes.",
    placeholder: 'Say "hello"\nnext line',
    sample: '{"name":"Ada"}\n',
    actionLabel: "Escape",
    run: sync(escapeJson),
  },
  {
    id: "json-unescape",
    name: "Unescape JSON",
    category: "json",
    blurb:
      "Reverse of Escape. Turns backslash-escapes into real characters. Also accepts a quoted JSON string.",
    placeholder: '{\\"name\\":\\"Ada\\"}',
    sample: '{\\"name\\":\\"Ada\\"}\n',
    actionLabel: "Unescape",
    run: sync(unescapeJson),
  },
  {
    id: "json-stringify",
    name: "Stringify",
    category: "json",
    blurb:
      "Wrap the input as a JSON string, the same as JSON.stringify on text. Includes the surrounding quotes.",
    placeholder: "hello\nworld",
    sample: 'hello "world"',
    actionLabel: "Stringify",
    run: sync(stringifyJson),
  },
  {
    id: "json-parse",
    name: "Parse JSON",
    category: "json",
    blurb:
      "Parse JSON. A JSON string becomes raw text. Objects and arrays are pretty-printed.",
    placeholder: '"hello\\nworld"',
    sample: '"{\\"name\\":\\"Ada\\"}"',
    actionLabel: "Parse",
    run: sync(parseJson),
  },
  {
    id: "json-validate",
    name: "Validate JSON",
    category: "json",
    blurb: "Check that the input is valid JSON and describe its shape.",
    placeholder: '{"ok":true}',
    sample: '{"ok":true,"n":1}',
    actionLabel: "Validate",
    run: sync(validateJson),
  },
  {
    id: "base64-encode",
    name: "Base64 encode",
    category: "encode",
    blurb: "Encode UTF-8 text as standard Base64.",
    placeholder: "hello",
    sample: "hello",
    actionLabel: "Encode",
    run: sync(encodeBase64),
  },
  {
    id: "base64-decode",
    name: "Base64 decode",
    category: "encode",
    blurb: "Decode standard or URL-safe Base64 to UTF-8 text. Whitespace is ignored.",
    placeholder: "aGVsbG8=",
    sample: "aGVsbG8=",
    actionLabel: "Decode",
    run: sync(decodeBase64),
  },
  {
    id: "base64url-encode",
    name: "Base64url encode",
    category: "encode",
    blurb: "Encode UTF-8 text as URL-safe Base64 without padding.",
    placeholder: "hello?",
    sample: "hello?",
    actionLabel: "Encode",
    run: sync(encodeBase64Url),
  },
  {
    id: "url-encode",
    name: "URL encode",
    category: "encode",
    blurb: "Percent-encode text with encodeURIComponent. Use this for query values.",
    placeholder: "a b&c=d",
    sample: "a b&c=d",
    actionLabel: "Encode",
    run: sync(encodeUrl),
  },
  {
    id: "url-decode",
    name: "URL decode",
    category: "encode",
    blurb: "Decode percent-encoding. Plus signs become spaces.",
    placeholder: "a%20b%26c%3Dd",
    sample: "a%20b%26c%3Dd",
    actionLabel: "Decode",
    run: sync(decodeUrl),
  },
  {
    id: "html-escape",
    name: "HTML escape",
    category: "encode",
    blurb: "Escape & < > \" ' as HTML entities.",
    placeholder: '<b>a & b</b>',
    sample: '<b>Tom & Jerry</b>',
    actionLabel: "Escape",
    run: sync(escapeHtml),
  },
  {
    id: "html-unescape",
    name: "HTML unescape",
    category: "encode",
    blurb: "Turn HTML entities, including numeric ones, back into characters.",
    placeholder: "&lt;b&gt;Tom &amp; Jerry&lt;/b&gt;",
    sample: "&lt;b&gt;Tom &amp; Jerry&lt;/b&gt;",
    actionLabel: "Unescape",
    run: sync(unescapeHtml),
  },
  {
    id: "hex-encode",
    name: "Text to hex",
    category: "encode",
    blurb: "Encode UTF-8 text as space-separated hex bytes.",
    placeholder: "hi",
    sample: "hi",
    actionLabel: "Encode",
    run: sync(textToHex),
  },
  {
    id: "hex-decode",
    name: "Hex to text",
    category: "encode",
    blurb: "Decode hex bytes to UTF-8 text. Spaces and 0x prefixes are ignored.",
    placeholder: "68 69",
    sample: "68 69",
    actionLabel: "Decode",
    run: sync(hexToText),
  },
  {
    id: "hash",
    name: "Hash",
    category: "encode",
    blurb: "SHA-1, SHA-256, and SHA-512 of the UTF-8 text. Computed in the browser.",
    placeholder: "hello",
    sample: "hello",
    actionLabel: "Hash",
    run: async (input) => {
      try {
        return { ok: true, output: await hashText(input) };
      } catch (err) {
        return { ok: false, error: toolErrorMessage(err) };
      }
    },
  },
  {
    id: "uuid",
    name: "UUID",
    category: "encode",
    blurb: "Generate a random UUID (version 4).",
    placeholder: "",
    sample: "",
    actionLabel: "Generate",
    generates: true,
    run: async () => runSync(newUuid),
  },
  {
    id: "url-parse",
    name: "URL parse",
    category: "web",
    blurb: "Split an absolute URL into protocol, host, path, query, and hash.",
    placeholder: "https://example.com/a?q=1#top",
    sample: "https://example.com/search?q=cats&page=2#results",
    actionLabel: "Parse",
    run: sync(parseUrl),
  },
  {
    id: "query-parse",
    name: "Query to JSON",
    category: "web",
    blurb: "Turn a query string, or the query of a full URL, into JSON.",
    placeholder: "q=cats&page=2",
    sample: "?q=cats&tag=a&tag=b",
    actionLabel: "Parse",
    run: sync(parseQuery),
  },
  {
    id: "query-build",
    name: "JSON to query",
    category: "web",
    blurb: "Build a query string from a JSON object. Arrays become repeated keys.",
    placeholder: '{"q":"cats","page":2}',
    sample: '{"q":"cats","tag":["a","b"]}',
    actionLabel: "Build",
    run: sync(buildQuery),
  },
  {
    id: "jwt-decode",
    name: "JWT decode",
    category: "web",
    blurb:
      "Show a JWT header and payload. The signature is not verified. A leading Bearer prefix is ignored.",
    placeholder: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.sig",
    sample:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0IiwibmFtZSI6IkFkYSIsImlhdCI6MTUxNjIzOTAyMn0.signature",
    actionLabel: "Decode",
    run: sync(decodeJwt),
  },
  {
    id: "html-strip",
    name: "Strip HTML",
    category: "web",
    blurb: "Remove tags, script, and style, then unescape entities.",
    placeholder: "<p>Hello <b>there</b></p>",
    sample: "<p>Hello <b>there</b> &amp; welcome</p>",
    actionLabel: "Strip",
    run: sync(stripHtml),
  },
  {
    id: "upper",
    name: "Uppercase",
    category: "text",
    blurb: "Convert text to uppercase.",
    placeholder: "Hello",
    sample: "Hello, world",
    actionLabel: "Uppercase",
    run: sync(toUpper),
  },
  {
    id: "lower",
    name: "Lowercase",
    category: "text",
    blurb: "Convert text to lowercase.",
    placeholder: "Hello",
    sample: "Hello, WORLD",
    actionLabel: "Lowercase",
    run: sync(toLower),
  },
  {
    id: "trim-lines",
    name: "Trim lines",
    category: "text",
    blurb: "Trim whitespace from the start and end of each line.",
    placeholder: "  a  \n b",
    sample: "  alpha  \n\tbeta\t",
    actionLabel: "Trim",
    run: sync(trimLines),
  },
  {
    id: "sort-lines",
    name: "Sort lines",
    category: "text",
    blurb: "Sort lines alphabetically.",
    placeholder: "b\na",
    sample: "banana\napple\ncherry",
    actionLabel: "Sort",
    run: sync(sortLines),
  },
  {
    id: "unique-lines",
    name: "Unique lines",
    category: "text",
    blurb: "Drop duplicate lines, keeping the first occurrence.",
    placeholder: "a\nb\na",
    sample: "a\nb\na\nb\nc",
    actionLabel: "Unique",
    run: sync(uniqueLines),
  },
  {
    id: "count",
    name: "Count",
    category: "text",
    blurb: "Count characters, words, and lines.",
    placeholder: "Hello world",
    sample: "Hello world\nsecond line",
    actionLabel: "Count",
    run: sync(countText),
  },
  {
    id: "unix-to-utc",
    name: "Unix to UTC",
    category: "time",
    blurb:
      "Convert a Unix timestamp to UTC. Values of 11 digits or more are treated as milliseconds.",
    placeholder: "1717232400",
    sample: "1717232400",
    actionLabel: "Convert",
    run: sync(unixToUtc),
  },
  {
    id: "utc-to-unix",
    name: "UTC to Unix",
    category: "time",
    blurb: "Convert a date to a Unix timestamp in seconds and milliseconds.",
    placeholder: "2024-06-01T12:00:00Z",
    sample: "2024-06-01T12:00:00Z",
    actionLabel: "Convert",
    run: sync(utcToUnix),
  },
  {
    id: "hex-to-rgb",
    name: "Hex to RGB",
    category: "data",
    blurb: "Convert #RGB, #RRGGBB, or #RRGGBBAA to CSS rgb() or rgba().",
    placeholder: "#1a2b3c",
    sample: "#1a2b3c",
    actionLabel: "Convert",
    run: sync(hexToRgb),
  },
  {
    id: "rgb-to-hex",
    name: "RGB to hex",
    category: "data",
    blurb: "Convert rgb(), rgba(), or r, g, b to a hex color.",
    placeholder: "rgb(26, 43, 60)",
    sample: "rgb(26, 43, 60)",
    actionLabel: "Convert",
    run: sync(rgbToHex),
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    category: "data",
    blurb: "Convert a JSON object, or an array of objects, to CSV.",
    placeholder: '[{"name":"Ada"}]',
    sample: '[{"name":"Ada","lang":"js"},{"name":"Linus","lang":"c"}]',
    actionLabel: "Convert",
    run: sync((input) => jsonToDelimited(input, ",")),
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    category: "data",
    blurb: "Convert CSV to a JSON array of objects. The first row is the header.",
    placeholder: "name,lang\nAda,js",
    sample: "name,lang\nAda,js\nLinus,c",
    actionLabel: "Convert",
    run: sync((input) => delimitedToJson(input, ",")),
  },
  {
    id: "csv-to-tsv",
    name: "CSV to TSV",
    category: "data",
    blurb: "Change commas to tabs, keeping quoted fields intact.",
    placeholder: "name,lang\nAda,js",
    sample: 'name,note\nAda,"hello, world"',
    actionLabel: "Convert",
    run: sync((input) => jsonToDelimited(delimitedToJson(input, ","), "\t")),
  },
  {
    id: "tsv-to-csv",
    name: "TSV to CSV",
    category: "data",
    blurb: "Change tabs to commas, quoting fields that need it.",
    placeholder: "name\tlang\nAda\tjs",
    sample: "name\tlang\nAda\tjs",
    actionLabel: "Convert",
    run: sync((input) => jsonToDelimited(delimitedToJson(input, "\t"), ",")),
  },
];

export function findTool(id: string): ToolDef | undefined {
  return TOOLS.find((tool) => tool.id === id);
}
